baseurl: "/"
languageCode: "en-us"
title: "MERGe Lab"
# theme: ""
# googleAnalytics: ""
# disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
publishdir: "docs"

menu:
  main:
    - name: People
      url:  "https://lillych.in"
      weight: 1
    - name: Research
      url: "https://lillych.in/research/"
      weight: 2
    - name: Resources
      url: "resources/"
      weight: 6

params:
  description: "MERGe Lab website"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
      endLevel: 4
      ordered: false
      startLevel: 2

