baseurl: "/"
languageCode: "en-us"
title: "MERGe Lab"
# theme: ""
# googleAnalytics: ""
# disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
publishdir: "docs"

menu:
  main:
    - name: People
      url:  "people/"
      weight: 1
    - name: Research
      url: "research/"
      weight: 2
    - name: Publications
      url: "publications/"
      weight: 3
    - name: News
      url: "news/"
      weight: 5
    - name: Resources
      url: "resources/"
      weight: 6
    - name: Lab
      url: "lab"
      parent: "Resources"
      weight: 3
    - name: Career
      url: "career"
      parent: "Resources"
      weight: 4

params:
  description: "MERGe Lab website"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
      endLevel: 4
      ordered: false
      startLevel: 1

